### PR TITLE
@W-10717926@ Accelerate/Feature | Salesforce Chatbot Global Template

### PR DESCRIPTION
**Pull request by amaskiellEG**
# Description

Replaces #41:

> This PR adds the Salesforce Chatbot template which interacts with the chatbot that is embedded on a client's website. It is based on a design from [Juliano Polito](https://bitbucket.org/julianopolito/autoopen-sdochat/src/master/) (SF POP team). The template requires that the client already has the chatbot installed on their website. It does not use any `html` or `css`. There are two websites that run the chatbot that can be used as a point of reference: [northerntrailoutfitters.com](https://www.northerntrailoutfitters.com/default/homepage) and [salesforce.com](https://www.salesforce.com/)

## Related Issues/Tickets

GUS: [W-10717926](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000pTsXVYA0/view)

#### Template:
- You can view the demo template in `training:amask`, **template name: [PR 42] Salesforce Chatbot**.

#### Campaign:
- You can view the demo campaigns which use this template in `training:amask`:
    - **campaign name: [PR 42] Salesforce Chatbot - TEST GROUP**
        - should be present in event response on any pages _except_ product detail pages
    - **campaign name: [PR 42] Salesforce Chatbot - CONTROL GROUP**
        - should only be in event response on product detail pages
_Note: you will need to force the SDK using this URL: https://cdn.evgnet.com/beacon/training/amask/scripts/evergage.min.js_

### Things to check for:
* **Mobile/smaller screen responsiveness:** Does the Template generally look good on smaller screens?
* **Template-specific documentation**: Is there sufficient information for a Template Developer to use the Global Template and customize it for their own use?
* **Campaign stats tracking:** Do impression stats fire for both the Control and Test experience?

### CODE REVIEW

**Review by dchouEG — CHANGES_REQUESTED** [review]
Tested using template in basic MVP campaign:
Normal speed using time on page of 10 seconds: Chatbot appears faster than 10 seconds. Impression recorded.
Normal speed using inactivity of 10 seconds: Chatbot appears faster than 10 seconds. Impression recorded.
Throttled Speed using time on page of 10 seconds: Chatbot never appears. No impressions. 
Throttled Speed using inactivity of 10 seconds: Chatbot never appears. No impressions.

**Comment by amaskiellEG** [comment]
@dchouEG - Ready for another review 🙂 

And just to leave my observations here:
- It makes sense that the template was seeming to ignore the trigger options: in an effort to DRY-up the code, I moved the `openChatBot` call outside of `handleTriggerEvent` which was resulting in the chatbot being opened as soon as `resolveWhenTrue` resolved rather than when the trigger option criteria were met.
- The reason for essentially nothing working with a throttled connection is that NTO was loading _waaayyyyyyyyyy_ slower than the `resolveWhenTrue` timeout. Therefore, I've changed the timeout value to 5 minutes (`(1000 * 60 * 5)`) and the interval value to 500 milliseconds.

**Review by dchouEG — APPROVED** [review]
Tested using template in basic MVP campaign:
Normal speed using time on page of 10 seconds: Chatbot appears in 10 seconds. Impression recorded.
Normal speed using inactivity of 10 seconds: Chatbot appears in 10 seconds. Impression recorded.
Throttled Speed using time on page of 10 seconds: Chatbot appears eventually. Impression recorded.
Throttled Speed using inactivity of 10 seconds: Chatbot appears eventually. Impression recorded.

LGTM!

**Review by dchouEG — DISMISSED** [review]

**Comment by amaskiellEG** [comment]
This may or may not need a security review but it might not hurt, considering the exposure this will have.

**Comment by amaskiellEG** [comment]
@cliffordlyon - Any chance someone will have time to give this a security review soon?

**Review by avkieu — DISMISSED** [review]
Looks good from a security perspective.

**Comment by amaskiellEG** [comment]
Following some conversations today, I added back the `scrollDepth` trigger option.

_Convo Links:_
_- initial question: https://salesforce-internal.slack.com/archives/C02TW0RAWAC/p1652712620993399_
_- conclusion: https://salesforce-internal.slack.com/archives/C02TW0RAWAC/p1652715736149649_

**Review by dchouEG — APPROVED** [review]
Just a note decimals are breaking the template but this is a separate bug to be fixed with serialization.

**Comment by astral303** [comment]
Security review passed.

**Pull request merged**
